# Generated by Django 3.2.13 on 2022-06-13 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('enterprise_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=250)),
                ('phone_number', models.BigIntegerField()),
                ('email_id', models.CharField(max_length=250)),
                ('company_logo', models.CharField(blank=True, max_length=250, null=True)),
                ('proprietor_name', models.CharField(max_length=250)),
                ('proprietor_email', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='enterprise_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='enterprise_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.enterprise')),
            ],
        ),
    ]
